# Generated by Django 6.0 on 2025-12-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(max_length=20, unique=True)),
                ('receiver_name', models.CharField(max_length=120)),
                ('delivery_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_type', models.CharField(choices=[('same_day', 'Same Day'), ('next_day', 'Next Day'), ('intercity', 'Intercity')], max_length=20)),
                ('status', models.CharField(default='created', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
        ),
    ]
